### ISSUE TITLE
Wie wird eine Idee als "dumm" oder "teilweise auch sinnvoll" eingestuft? Sind Pull Requests erwünscht?

### ISSUE THREAD

**Issue by moqmar** [t-aus-m/ListeDerDummenIdeen#1]

**Comment by t-aus-m** [comment]
~~Eine Idee ist dumm, wenn wir darauf kommen. 😅~~ 

Spaß beiseite: Dumme Ideen sind solche,  bei denen man denkt: _"Was ist das denn für ne dumme Idee?"_  oder alternativ: _"Das ist so abgefahren, das will ich umsetzen!"_  

Teilweise auch sinnvolle Ideen sind die, bei denen man aus der dummen Idee einen Mehrwert ableiten kann.

Pull Requests sind herzlich willkommen, werden aber nur gemerged, wenn sie als umsetzungswürdig eingestuft werden.

@zottelchin Geht die Regelung klar fur dich?

**Comment by zottelchin** [comment]
Jo, die Definition finde ich gut 👍
